/**
 * Decides which file a media item should be played from in the renderer.
 *
 * Chromium can decode H.264/VP9/AV1 + AAC/MP3/Opus/FLAC natively (probe.browserPlayable);
 * everything else must go through the proxy generated by the main process.
 */
import type { MediaItem, Rational } from '../../shared/model';

export interface PlaybackPathResolution {
  /** Absolute filesystem path to play, or null when nothing is playable. */
  path: string | null;
  usingProxy: boolean;
  /** Human readable explanation when a non-obvious choice was made or nothing is playable. */
  reason?: string;
}

const DEFAULT_FPS: Rational = { num: 24, den: 1 };

export function resolvePlaybackPath(media: MediaItem, useProxies: boolean): PlaybackPathResolution {
  if (media.offline) return { path: null, usingProxy: false, reason: 'media offline' };
  const proxyReady = media.proxy?.status === 'ready' && !!media.proxy.path;
  const proxyPath = proxyReady ? media.proxy.path! : null;

  if (useProxies && proxyPath) return { path: proxyPath, usingProxy: true };

  const playable = media.probe?.browserPlayable === true;
  if (playable) return { path: media.path, usingProxy: false };

  if (proxyPath) {
    return { path: proxyPath, usingProxy: true, reason: 'original not decodable; using proxy' };
  }

  if (!media.probe) {
    return { path: null, usingProxy: false, reason: media.probeError ? `probe failed: ${media.probeError}` : 'not probed yet' };
  }
  const why = media.probe.playabilityReason ? ` (${media.probe.playabilityReason})` : '';
  const proxyState = media.proxy?.status ?? 'none';
  const proxyHint = proxyState === 'running' || proxyState === 'queued'
    ? '; proxy in progress'
    : proxyState === 'failed'
      ? `; proxy failed${media.proxy.error ? ': ' + media.proxy.error : ''}`
      : '; generate a proxy to preview';
  return { path: null, usingProxy: false, reason: `original not decodable${why}${proxyHint}` };
}

/** Frame rate of the media's video stream; falls back to 24 fps for audio/images/unknown. */
export function mediaFps(media: MediaItem | undefined): Rational {
  const v = media?.probe?.video;
  if (v) {
    const pick = v.fps && v.fps.num > 0 && v.fps.den > 0 ? v.fps : v.avgFps;
    if (pick && pick.num > 0 && pick.den > 0) return pick;
  }
  return DEFAULT_FPS;
}

/** Duration in seconds; Infinity for still images, 0 when unknown. */
export function mediaDurationSeconds(media: MediaItem | undefined): number {
  if (!media) return 0;
  if (media.kind === 'image') return Infinity;
  return media.probe?.duration ?? 0;
}

/** Pixel size of the video stream when known. */
export function mediaSize(media: MediaItem | undefined): { width: number; height: number } | null {
  const v = media?.probe?.video;
  if (!v || !v.width || !v.height) return null;
  return { width: v.width, height: v.height };
}

export function hasAudio(media: MediaItem | undefined): boolean {
  return (media?.probe?.audio.length ?? 0) > 0;
}
