/**
 * Decides which file a media item should be played from in the renderer.
 *
 * Chromium can decode H.264/VP9/AV1 + AAC/MP3/Opus/FLAC natively (probe.browserPlayable);
 * everything else must go through the proxy generated by the main process.
 */
import type { MediaItem, Rational } from '../../shared/model';

export interface PlaybackPathResolution {
  /** Absolute filesystem path to play, or null when nothing is playable. */
  path: string | null;
  usingProxy: boolean;
  /**
   * Seconds to ADD to a (container-relative) source time to get the <video>/<audio> element's
   * currentTime, and to subtract when reading it back. Chromium's media timeline is the file's
   * absolute pts, so an original whose container start_time is not 0 (e.g. MPEG-TS remuxes,
   * `-output_ts_offset` files) is offset by that start time; proxies are 0-based (offset 0).
   * Missing means 0.
   */
  timeOffset?: number;
  /** Human readable explanation when a non-obvious choice was made or nothing is playable. */
  reason?: string;
  /** True when `path` is a still image to draw with an <img> (the original, or its PNG proxy; no <video>, no audio). */
  isImage?: boolean;
}

/**
 * Still-image extensions Chromium decodes in an <img> (drawn directly; never proxied). Every other still (TIFF, TGA,
 * EXR, PSD, JPEG XL, HEIC, ...) is previewed from a PNG proxy that FFmpeg decodes on import (electron/media/proxy.ts),
 * so the preview shows what the export decodes. AVIF is proxied too although Electron 33 decodes it: Chromium applies
 * the AVIF `irot` / `imir` orientation and FFmpeg 6.1 does not, so a rotated AVIF drawn directly would preview
 * rotated and export unrotated (bugs/closed/2026-10-07-avif-preview-orientation-differs-from-export.md).
 */
export const DISPLAYABLE_IMAGE_EXTS: readonly string[] = ['png', 'jpg', 'jpeg', 'jpe', 'jfif', 'webp', 'gif', 'bmp'];

/** Still-image extensions (FFmpeg decodes them all); see STILL_IMAGE_EXTS in src/state/store.ts. */
const STILL_EXTS: readonly string[] = [
  'png', 'apng', 'jpg', 'jpeg', 'jpe', 'jfif', 'webp', 'bmp', 'tif', 'tiff', 'gif', 'heic', 'heif', 'avif',
  'jxl', 'tga', 'exr', 'psd', 'dpx', 'sgi', 'pcx', 'ppm', 'pgm', 'pbm', 'pam', 'qoi', 'hdr', 'jp2', 'j2k',
];

function fileExt(path: string): string {
  const base = path.split(/[\\/]/).pop() ?? '';
  const dot = base.lastIndexOf('.');
  return dot > 0 ? base.slice(dot + 1).toLowerCase() : '';
}

/**
 * A still image: classified on import, or probed as one. A probe saved before stills were detected in every container
 * (an AVIF read as a browser-playable `mov`) counts when it is a picture without duration or audio in an image file.
 */
export function isStillImage(media: MediaItem | undefined): boolean {
  if (!media) return false;
  if (media.kind === 'image' || media.probe?.playabilityReason === 'still image') return true;
  const p = media.probe;
  return !!p?.video && !(p.duration > 0) && p.audio.length === 0 && STILL_EXTS.includes(fileExt(media.path));
}

/** A still image the renderer can draw directly from the original file (png/jpg/jpeg/webp/gif/bmp). */
export function isDisplayableImage(media: MediaItem | undefined): boolean {
  return isStillImage(media) && DISPLAYABLE_IMAGE_EXTS.includes(fileExt(media!.path));
}

/**
 * Whether previewing `media` needs a proxy: probed, and either a still Chromium cannot draw (previewed from a PNG
 * proxy) or a video/audio file it cannot decode.
 */
export function mediaNeedsProxyForPreview(media: MediaItem | undefined): boolean {
  if (!media || media.offline || !media.probe) return false;
  if (isStillImage(media)) return !isDisplayableImage(media);
  return !media.probe.browserPlayable;
}

const DEFAULT_FPS: Rational = { num: 24, den: 1 };

/**
 * The audio stream the export renders for a requested one (renderGraph.ts `audioStreamIndex`): `want` when it is an
 * audio stream of the probed file, otherwise the first audio stream; null when the file has no audio. Unprobed media
 * keeps `want` (null when unset). `want` is `clip.audioStream ?? media.preferredAudioStream` for a clip.
 */
export function resolveAudioStream(media: MediaItem | undefined, want: number | undefined): number | null {
  const probe = media?.probe;
  if (!probe) return want ?? null;
  if (probe.audio.length === 0) return null;
  if (want !== undefined && probe.audio.some((a) => a.index === want)) return want;
  return probe.audio[0].index;
}

/** File-name suffix of a proxy that carries every audio stream (electron/media/proxy.ts proxyOutputPath). */
const ALL_STREAMS_PROXY = /_all\.mp4$/i;
/** Older single-stream proxies: `<key>_<h>p_a<N>.mp4` carries stream N. */
const ONE_STREAM_PROXY = /_a(\d+)\.mp4$/i;

/**
 * Absolute indexes of the source audio streams the media's proxy carries, in the proxy's track order. A `_all` proxy
 * carries every stream of the probe; an older one carries one: its `_a<N>` suffix, else the stream recorded on the
 * proxy, else the first audio stream (what ffmpeg mapped by default).
 */
export function proxyAudioStreams(media: MediaItem): number[] {
  const all = media.probe?.audio.map((a) => a.index) ?? [];
  const p = media.proxy.path ?? '';
  if (ALL_STREAMS_PROXY.test(p)) return all;
  const m = ONE_STREAM_PROXY.exec(p);
  if (m) return [Number(m[1])];
  if (typeof media.proxy.audioStream === 'number') return [media.proxy.audioStream];
  return all.slice(0, 1);
}

/**
 * Which audio track of the played file (`usingProxy`: the proxy, else the original) carries the stream the export
 * renders for `want` (see resolveAudioStream): its ordinal among the file's audio tracks. Chromium lists a file's
 * audio tracks in stream order, and direct-play files have only decodable streams (evaluatePlayability), so the
 * ordinal among `probe.audio` is the HTMLMediaElement.audioTracks index. A proxy lacking the stream plays its first
 * track. -1: nothing to choose (no audio, one audio track, or not probed), keep the element's default track.
 */
export function audioTrackOrdinal(media: MediaItem, usingProxy: boolean, want: number | undefined): number {
  const audio = media.probe?.audio;
  if (!audio || audio.length < 2) return -1; // a proxy never carries more streams than the source
  const abs = resolveAudioStream(media, want);
  if (abs === null) return -1;
  if (!usingProxy) return Math.max(0, audio.findIndex((a) => a.index === abs)); // runs per frame: no allocation
  const tracks = proxyAudioStreams(media);
  return tracks.length < 2 ? -1 : Math.max(0, tracks.indexOf(abs));
}

/**
 * Audio stream to draw a clip's waveform from: the stream the export renders for `want` (see resolveAudioStream), or
 * undefined for the file's first audio stream (the waveform cached before streams were selectable).
 */
export function waveformStream(media: MediaItem | undefined, want: number | undefined): number | undefined {
  const audio = media?.probe?.audio;
  if (!audio || audio.length < 2) return undefined;
  const abs = resolveAudioStream(media, want);
  return abs === null || abs === audio[0].index ? undefined : abs;
}

/**
 * True when the media has a proxy (ready / failed) that does not carry a stream the preview needs, so it would play
 * the wrong language / commentary track. `wants`: the requested streams (each resolved as the export does); default
 * the media's preferred stream. Proxies carrying every stream are never stale.
 */
export function proxyStreamStale(media: MediaItem, wants: readonly (number | undefined)[] = [media.preferredAudioStream]): boolean {
  if (media.proxy.status !== 'ready' && media.proxy.status !== 'failed') return false;
  const have = proxyAudioStreams(media);
  if (have.length === 0) return false;
  return wants.some((w) => { const abs = resolveAudioStream(media, w); return abs !== null && !have.includes(abs); });
}

/** One-line preview status for the Media Inspector / info footer: direct, still image, or needs a proxy. */
export function previewPlaybackLabel(media: MediaItem): { direct: boolean; text: string } {
  const p = media.probe;
  if (isDisplayableImage(media)) return { direct: true, text: 'Direct (still image)' };
  if (isStillImage(media)) return { direct: false, text: `Proxy required — ${(fileExt(media.path) || 'this').toUpperCase()} image (previewed as PNG)` };
  if (!p || p.browserPlayable) return { direct: true, text: 'Direct' };
  return { direct: false, text: `Proxy required${p.playabilityReason ? ` — ${p.playabilityReason}` : ''}` };
}

export function resolvePlaybackPath(media: MediaItem, useProxies: boolean): PlaybackPathResolution {
  if (media.offline) return { path: null, usingProxy: false, reason: 'media offline' };
  if (isDisplayableImage(media)) return { path: media.path, usingProxy: false, timeOffset: 0, isImage: true };
  const proxyReady = media.proxy?.status === 'ready' && !!media.proxy.path;
  const proxyPath = proxyReady ? media.proxy.path! : null;
  if (isStillImage(media) && media.probe) {
    // Chromium cannot draw this format: the PNG proxy, whatever the proxies toggle (a proxy beats nothing).
    if (proxyPath) return { path: proxyPath, usingProxy: true, timeOffset: 0, isImage: true };
    const ext = (fileExt(media.path) || 'unknown').toUpperCase();
    return { path: null, usingProxy: false, reason: `${ext} image needs a preview proxy${proxyHint(media)}` };
  }

  if (useProxies && proxyPath) return { path: proxyPath, usingProxy: true, timeOffset: 0 };

  const playable = media.probe?.browserPlayable === true;
  if (playable) return { path: media.path, usingProxy: false, timeOffset: mediaTimeOffset(media, false) };

  if (proxyPath) {
    return { path: proxyPath, usingProxy: true, timeOffset: 0, reason: 'original not decodable; using proxy' };
  }

  if (!media.probe) {
    return { path: null, usingProxy: false, reason: media.probeError ? `probe failed: ${media.probeError}` : 'not probed yet' };
  }
  const why = media.probe.playabilityReason ? ` (${media.probe.playabilityReason})` : '';
  return { path: null, usingProxy: false, reason: `original not decodable${why}${proxyHint(media)}` };
}

/** "; proxy in progress" / "; proxy failed: ..." / "; generate a proxy to preview". */
function proxyHint(media: MediaItem): string {
  const proxyState = media.proxy?.status ?? 'none';
  return proxyState === 'running' || proxyState === 'queued'
    ? '; proxy in progress'
    : proxyState === 'failed'
      ? `; proxy failed${media.proxy.error ? ': ' + media.proxy.error : ''}`
      : '; generate a proxy to preview';
}

/**
 * Element-time offset for playing `media` (see PlaybackPathResolution.timeOffset): the container
 * start_time for originals, 0 for proxies (which ffmpeg writes 0-based, relative to the container start).
 */
export function mediaTimeOffset(media: MediaItem | undefined, usingProxy: boolean): number {
  if (usingProxy) return 0;
  const st = media?.probe?.startTime;
  return typeof st === 'number' && Number.isFinite(st) && st > 0 ? st : 0;
}

/** Source time (container-relative seconds) -> media element currentTime. */
export function toElementTime(sourceTime: number, offset: number | undefined): number {
  return sourceTime + (offset ?? 0);
}

/** Media element currentTime -> source time (container-relative seconds). */
export function fromElementTime(elementTime: number, offset: number | undefined): number {
  return elementTime - (offset ?? 0);
}

/**
 * Clamp an element-time seek target to the playable span of the element: [offset, duration).
 * When the original has a start offset, Chromium's reported `duration` is not a reliable end
 * (it is neither the stream length nor offset + length), so only the lower bound is enforced and
 * the element clamps past-the-end seeks itself.
 */
export function clampElementTime(t: number, elementDuration: number, offset: number | undefined): number {
  const off = offset ?? 0;
  if (off === 0 && Number.isFinite(elementDuration) && elementDuration > 0) return Math.max(0, Math.min(elementDuration - 0.001, t));
  return Math.max(off, t);
}

/** Frame rate of the media's video stream; falls back to 24 fps for audio/images/unknown. */
export function mediaFps(media: MediaItem | undefined): Rational {
  const v = media?.probe?.video;
  if (v) {
    const pick = v.fps && v.fps.num > 0 && v.fps.den > 0 ? v.fps : v.avgFps;
    if (pick && pick.num > 0 && pick.den > 0) return pick;
  }
  return DEFAULT_FPS;
}

/** Duration in seconds; Infinity for still images, 0 when unknown. */
export function mediaDurationSeconds(media: MediaItem | undefined): number {
  if (!media) return 0;
  if (media.kind === 'image') return Infinity;
  return media.probe?.duration ?? 0;
}

/** Pixel size of the video stream when known. */
export function mediaSize(media: MediaItem | undefined): { width: number; height: number } | null {
  const v = media?.probe?.video;
  if (!v || !v.width || !v.height) return null;
  return { width: v.width, height: v.height };
}

export function hasAudio(media: MediaItem | undefined): boolean {
  return (media?.probe?.audio.length ?? 0) > 0;
}
