/**
 * Decides which file a media item should be played from in the renderer.
 *
 * Chromium can decode H.264/VP9/AV1 + AAC/MP3/Opus/FLAC natively (probe.browserPlayable);
 * everything else must go through the proxy generated by the main process.
 */
import type { MediaItem, Rational } from '../../shared/model';

export interface PlaybackPathResolution {
  /** Absolute filesystem path to play, or null when nothing is playable. */
  path: string | null;
  usingProxy: boolean;
  /**
   * Seconds to ADD to a (container-relative) source time to get the <video>/<audio> element's
   * currentTime, and to subtract when reading it back. Chromium's media timeline is the file's
   * absolute pts, so an original whose container start_time is not 0 (e.g. MPEG-TS remuxes,
   * `-output_ts_offset` files) is offset by that start time; proxies are 0-based (offset 0).
   * Missing means 0.
   */
  timeOffset?: number;
  /** Human readable explanation when a non-obvious choice was made or nothing is playable. */
  reason?: string;
  /** True when `path` is a still image to draw with an <img> (no <video>, no audio, no proxy). */
  isImage?: boolean;
}

/** Still-image extensions Chromium decodes in an <img> (drawn directly; never proxied). */
export const DISPLAYABLE_IMAGE_EXTS: readonly string[] = ['png', 'jpg', 'jpeg', 'webp', 'gif', 'bmp'];

function fileExt(path: string): string {
  const base = path.split(/[\\/]/).pop() ?? '';
  const dot = base.lastIndexOf('.');
  return dot > 0 ? base.slice(dot + 1).toLowerCase() : '';
}

/** A still image (classified on import, or probed as one). */
export function isStillImage(media: MediaItem | undefined): boolean {
  return !!media && (media.kind === 'image' || media.probe?.playabilityReason === 'still image');
}

/** A still image the renderer can draw directly from the original file (png/jpg/jpeg/webp/gif/bmp). */
export function isDisplayableImage(media: MediaItem | undefined): boolean {
  return isStillImage(media) && DISPLAYABLE_IMAGE_EXTS.includes(fileExt(media!.path));
}

/**
 * Whether previewing `media` needs a proxy: probed, not decodable by Chromium, and not a still image
 * (images are drawn directly, or not at all — a proxy job cannot transcode a frame without duration).
 */
export function mediaNeedsProxyForPreview(media: MediaItem | undefined): boolean {
  return !!media && !media.offline && !!media.probe && !media.probe.browserPlayable && !isStillImage(media);
}

const DEFAULT_FPS: Rational = { num: 24, den: 1 };

/**
 * Audio stream the media's proxy carries: recorded on the proxy, else parsed from the cache file name
 * (`<key>_<h>p_a<N>.mp4`), else the first audio stream (what ffmpeg maps by default).
 */
export function proxyAudioStream(media: MediaItem): number | undefined {
  if (typeof media.proxy.audioStream === 'number') return media.proxy.audioStream;
  const m = media.proxy.path ? /_a(\d+)\.mp4$/i.exec(media.proxy.path) : null;
  if (m) return Number(m[1]);
  return media.probe?.audio[0]?.index;
}

/**
 * True when the media has a proxy (ready / failed) that was built for a different audio stream than the media's
 * preferred one, so the preview would play the wrong language / commentary track.
 */
export function proxyStreamStale(media: MediaItem): boolean {
  if (media.proxy.status !== 'ready' && media.proxy.status !== 'failed') return false;
  const want = media.preferredAudioStream ?? media.probe?.audio[0]?.index;
  const have = proxyAudioStream(media);
  return want !== undefined && have !== undefined && want !== have;
}

/** One-line preview status for the Media Inspector / info footer: direct, still image, or needs a proxy. */
export function previewPlaybackLabel(media: MediaItem): { direct: boolean; text: string } {
  const p = media.probe;
  if (isDisplayableImage(media)) return { direct: true, text: 'Direct (still image)' };
  if (isStillImage(media)) return { direct: false, text: 'Not previewable — convert the image to PNG or JPEG (export still works)' };
  if (!p || p.browserPlayable) return { direct: true, text: 'Direct' };
  return { direct: false, text: `Proxy required${p.playabilityReason ? ` — ${p.playabilityReason}` : ''}` };
}

export function resolvePlaybackPath(media: MediaItem, useProxies: boolean): PlaybackPathResolution {
  if (media.offline) return { path: null, usingProxy: false, reason: 'media offline' };
  if (isDisplayableImage(media)) return { path: media.path, usingProxy: false, timeOffset: 0, isImage: true };
  if (isStillImage(media) && media.probe) {
    return { path: null, usingProxy: false, reason: `image format not previewable (${fileExt(media.path) || 'unknown'}); convert to PNG or JPEG` };
  }
  const proxyReady = media.proxy?.status === 'ready' && !!media.proxy.path;
  const proxyPath = proxyReady ? media.proxy.path! : null;

  if (useProxies && proxyPath) return { path: proxyPath, usingProxy: true, timeOffset: 0 };

  const playable = media.probe?.browserPlayable === true;
  if (playable) return { path: media.path, usingProxy: false, timeOffset: mediaTimeOffset(media, false) };

  if (proxyPath) {
    return { path: proxyPath, usingProxy: true, timeOffset: 0, reason: 'original not decodable; using proxy' };
  }

  if (!media.probe) {
    return { path: null, usingProxy: false, reason: media.probeError ? `probe failed: ${media.probeError}` : 'not probed yet' };
  }
  const why = media.probe.playabilityReason ? ` (${media.probe.playabilityReason})` : '';
  const proxyState = media.proxy?.status ?? 'none';
  const proxyHint = proxyState === 'running' || proxyState === 'queued'
    ? '; proxy in progress'
    : proxyState === 'failed'
      ? `; proxy failed${media.proxy.error ? ': ' + media.proxy.error : ''}`
      : '; generate a proxy to preview';
  return { path: null, usingProxy: false, reason: `original not decodable${why}${proxyHint}` };
}

/**
 * Element-time offset for playing `media` (see PlaybackPathResolution.timeOffset): the container
 * start_time for originals, 0 for proxies (which ffmpeg writes 0-based, relative to the container start).
 */
export function mediaTimeOffset(media: MediaItem | undefined, usingProxy: boolean): number {
  if (usingProxy) return 0;
  const st = media?.probe?.startTime;
  return typeof st === 'number' && Number.isFinite(st) && st > 0 ? st : 0;
}

/** Source time (container-relative seconds) -> media element currentTime. */
export function toElementTime(sourceTime: number, offset: number | undefined): number {
  return sourceTime + (offset ?? 0);
}

/** Media element currentTime -> source time (container-relative seconds). */
export function fromElementTime(elementTime: number, offset: number | undefined): number {
  return elementTime - (offset ?? 0);
}

/**
 * Clamp an element-time seek target to the playable span of the element: [offset, duration).
 * When the original has a start offset, Chromium's reported `duration` is not a reliable end
 * (it is neither the stream length nor offset + length), so only the lower bound is enforced and
 * the element clamps past-the-end seeks itself.
 */
export function clampElementTime(t: number, elementDuration: number, offset: number | undefined): number {
  const off = offset ?? 0;
  if (off === 0 && Number.isFinite(elementDuration) && elementDuration > 0) return Math.max(0, Math.min(elementDuration - 0.001, t));
  return Math.max(off, t);
}

/** Frame rate of the media's video stream; falls back to 24 fps for audio/images/unknown. */
export function mediaFps(media: MediaItem | undefined): Rational {
  const v = media?.probe?.video;
  if (v) {
    const pick = v.fps && v.fps.num > 0 && v.fps.den > 0 ? v.fps : v.avgFps;
    if (pick && pick.num > 0 && pick.den > 0) return pick;
  }
  return DEFAULT_FPS;
}

/** Duration in seconds; Infinity for still images, 0 when unknown. */
export function mediaDurationSeconds(media: MediaItem | undefined): number {
  if (!media) return 0;
  if (media.kind === 'image') return Infinity;
  return media.probe?.duration ?? 0;
}

/** Pixel size of the video stream when known. */
export function mediaSize(media: MediaItem | undefined): { width: number; height: number } | null {
  const v = media?.probe?.video;
  if (!v || !v.width || !v.height) return null;
  return { width: v.width, height: v.height };
}

export function hasAudio(media: MediaItem | undefined): boolean {
  return (media?.probe?.audio.length ?? 0) > 0;
}
