/**
 * OCR of bitmap subtitle streams (PGS / VobSub / DVB / XSUB): the shared contract.
 *
 * - Which subtitle codecs are bitmaps ReCut can read with OCR (`OCR_SUBTITLE_CODECS`).
 * - The language-data manifest (`OCR_LANGUAGES`): Tesseract `tessdata_fast` files, pinned to one commit,
 *   with their exact size and SHA-256 (regenerate with `node scripts/ocr-manifest.mjs --write`).
 * - Request / result / language-state types used over IPC (shared/ipc.ts).
 * - Mapping between track language tags (ISO 639-2/B, 639-2/T, 639-1) and tessdata codes.
 *
 * Pure: no DOM, no Node.
 */
import type { ID, SubtitleCue } from './model';

/** Subtitle codecs (ffprobe `codec_name`) that carry images, which ReCut turns into text with OCR. */
export const OCR_SUBTITLE_CODECS = ['hdmv_pgs_subtitle', 'dvd_subtitle', 'dvb_subtitle', 'xsub'] as const;
export type OcrSubtitleCodec = (typeof OCR_SUBTITLE_CODECS)[number];

export function isOcrCodec(codec: string | undefined | null): codec is OcrSubtitleCodec {
  return typeof codec === 'string' && (OCR_SUBTITLE_CODECS as readonly string[]).includes(codec);
}

/** tessdata_fast commit every language file is pinned to (sizes and hashes in OCR_LANGUAGES are for this commit). */
export const TESSDATA_COMMIT = '87416418657359cb625c412a48b6e1d6d41c29bd';
/** Base URL of the pinned language files; a file's URL is `TESSDATA_BASE + file`. */
export const TESSDATA_BASE = `https://raw.githubusercontent.com/tesseract-ocr/tessdata_fast/${TESSDATA_COMMIT}/`;

/** One installable OCR language. */
export interface OcrLanguageInfo {
  /** tessdata code (`eng`, `chi_sim`, ...), also the file stem. */
  code: string;
  /** English display name. */
  name: string;
  /** File name under TESSDATA_BASE and in the local tessdata folder (`<code>.traineddata`). */
  file: string;
  /** Exact size in bytes. */
  bytes: number;
  /** Lower-case hex SHA-256 of the file. */
  sha256: string;
}

/**
 * Installable languages, sorted by name. Generated by scripts/ocr-manifest.mjs from TESSDATA_BASE: edit the
 * language list in that script, not the entries below.
 */
// <ocr-manifest>
export const OCR_LANGUAGES: readonly OcrLanguageInfo[] = [
  { code: 'afr', name: 'Afrikaans', file: 'afr.traineddata', bytes: 2652786, sha256: '126d480bfae95be2a911ed4916465e27bde75fea2da631e21b96762e5f239646' },
  { code: 'sqi', name: 'Albanian', file: 'sqi.traineddata', bytes: 1874705, sha256: '1d89621d9afe8ddf35b403ecf8951edea52c3a960d241f287b1a7b2c5ba8daac' },
  { code: 'ara', name: 'Arabic', file: 'ara.traineddata', bytes: 1432056, sha256: 'e3206d3dc87fd50c24a0fb9f01838615911d25168f4e64415244b67d2bb3e729' },
  { code: 'hye', name: 'Armenian', file: 'hye.traineddata', bytes: 3463717, sha256: 'b701d0d95799a716143dedb0197504e56f27a1bb133d6607ff5778c6988cb67c' },
  { code: 'eus', name: 'Basque', file: 'eus.traineddata', bytes: 5175921, sha256: '40e7418296c355d9fd9ca843d115c51e740089e576e887443e61704823cd6624' },
  { code: 'bel', name: 'Belarusian', file: 'bel.traineddata', bytes: 3692098, sha256: '9c6668a0b202f3dcfe074b64620d108e1902ca7498a40b5a11b4a3da6112d58f' },
  { code: 'ben', name: 'Bengali', file: 'ben.traineddata', bytes: 855841, sha256: '31163084c279aaebd376216f0c3d5c17ad4b5fee8db49dae79c20000b5de5964' },
  { code: 'bos', name: 'Bosnian', file: 'bos.traineddata', bytes: 2498242, sha256: '6cc8cc87cf1afbfa6a41febb725dbadb14bed96a46685906440a6eb8a7892f04' },
  { code: 'bul', name: 'Bulgarian', file: 'bul.traineddata', bytes: 1675212, sha256: 'aebc9b0fcc8cfaf8a9f38a02bb7b85052bd850744696a2c11cf0081820e5b21e' },
  { code: 'cat', name: 'Catalan', file: 'cat.traineddata', bytes: 1146012, sha256: '250db73cd5b380d2798581295dc12f20d0828cdb335a65d833d12dfdbf57117d' },
  { code: 'chi_sim', name: 'Chinese (Simplified)', file: 'chi_sim.traineddata', bytes: 2469156, sha256: 'a5fcb6f0db1e1d6d8522f39db4e848f05984669172e584e8d76b6b3141e1f730' },
  { code: 'chi_tra', name: 'Chinese (Traditional)', file: 'chi_tra.traineddata', bytes: 2366642, sha256: '529c5b5797d64b126065cd55f2bb4c7fd7b15790798091b1ff259941a829330b' },
  { code: 'hrv', name: 'Croatian', file: 'hrv.traineddata', bytes: 4103348, sha256: '9e515d9832ce259dbab550b1cc6b998f8b929faf2edacaaca981b05adb130571' },
  { code: 'ces', name: 'Czech', file: 'ces.traineddata', bytes: 3795684, sha256: '934bcaf97ef3348413263331131c9fa7f55f30db333c711929c124fb635f7e1b' },
  { code: 'dan', name: 'Danish', file: 'dan.traineddata', bytes: 2580059, sha256: 'acb1fd074487a31d1294fcdfd7d7c673467ffd8aeacb2ccd61ebcbf04eb4e2fa' },
  { code: 'nld', name: 'Dutch', file: 'nld.traineddata', bytes: 6050296, sha256: 'ced0e5e046a84c908a6aa7accbef9a232c4a5d9a8276691b81c6ee64d02963f6' },
  { code: 'eng', name: 'English', file: 'eng.traineddata', bytes: 4113088, sha256: '7d4322bd2a7749724879683fc3912cb542f19906c83bcc1a52132556427170b2' },
  { code: 'est', name: 'Estonian', file: 'est.traineddata', bytes: 4458101, sha256: '515d4a773682b286369511e83fe412bcff16a92a886f99c761c1d760a7e30456' },
  { code: 'fil', name: 'Filipino', file: 'fil.traineddata', bytes: 1841715, sha256: '2b17f68014ab44b88b5e2334ebcd0ce0090d9af7c6fbef6fab22e0bbd9a934dd' },
  { code: 'fin', name: 'Finnish', file: 'fin.traineddata', bytes: 7865732, sha256: '61a04cd62b507c3d9ae0e1cda399e6715ebf49dea9df47897c8acdcd3bd3e13c' },
  { code: 'fra', name: 'French', file: 'fra.traineddata', bytes: 1130365, sha256: 'ced037562e8c80c13122dece28dd477d399af80911a28791a66a63ac1e3445ca' },
  { code: 'glg', name: 'Galician', file: 'glg.traineddata', bytes: 2554555, sha256: '7947619c5544d86849f563bd737ad90dbea9f5319fbd838c4747a7a1cd40b260' },
  { code: 'kat', name: 'Georgian', file: 'kat.traineddata', bytes: 2524769, sha256: '557abb6f1c68bc1b286f1bdd00bb6b82f85a427a91899807dab6c2f6c7986731' },
  { code: 'deu', name: 'German', file: 'deu.traineddata', bytes: 1525436, sha256: '19d219bbb6672c869d20a9636c6816a81eb9a71796cb93ebe0cb1530e2cdb22d' },
  { code: 'ell', name: 'Greek', file: 'ell.traineddata', bytes: 1419514, sha256: '4fba8a0b461038d51f1c20d043d4f2ac38c4e778f1b90830847f7bd8fa3ba726' },
  { code: 'heb', name: 'Hebrew', file: 'heb.traineddata', bytes: 961404, sha256: '11f9e43ab227f786352a50f75c94c2e9906f1baba86d93276da19da7ce0904db' },
  { code: 'hin', name: 'Hindi', file: 'hin.traineddata', bytes: 1122751, sha256: '4c73ffc59d497c186b19d1e90f5d721d678ea6b2e277b719bee4e2af12271825' },
  { code: 'hun', name: 'Hungarian', file: 'hun.traineddata', bytes: 5296273, sha256: '35067e7cfe102dcdc953f9a758fdfaa6296b17a1ee6d874ee780fa306430b9fb' },
  { code: 'isl', name: 'Icelandic', file: 'isl.traineddata', bytes: 2278973, sha256: '5ec828c363f3f0062c3caf08216677cf5f3c0c981b05fab445123a16b98f10a9' },
  { code: 'ind', name: 'Indonesian', file: 'ind.traineddata', bytes: 1122661, sha256: '69786901da87ab8766c1ea7fbb10b28f2110c14da3f6c8f2735df131fba95d88' },
  { code: 'gle', name: 'Irish', file: 'gle.traineddata', bytes: 1181824, sha256: '2fe9ba6119aac7e2a20d6cfb69ed91afe9520f41bc7e3a903f84280f2663858d' },
  { code: 'ita', name: 'Italian', file: 'ita.traineddata', bytes: 2701314, sha256: 'b8f89e1e785118dac4d51ae042c029a64edb5c3ee42ef73027a6d412748d8827' },
  { code: 'jpn', name: 'Japanese', file: 'jpn.traineddata', bytes: 2471260, sha256: '1f5de9236d2e85f5fdf4b3c500f2d4926f8d9449f28f5394472d9e8d83b91b4d' },
  { code: 'kor', name: 'Korean', file: 'kor.traineddata', bytes: 1677415, sha256: '6b85e11d9bbf07863b97b3523b1b112844c43e713df8b66418a081fd1060b3b2' },
  { code: 'lav', name: 'Latvian', file: 'lav.traineddata', bytes: 2717247, sha256: '7d9eaf22254b381f18b806cd6cb647862a397a7221adbce3e22cc421793a8847' },
  { code: 'lit', name: 'Lithuanian', file: 'lit.traineddata', bytes: 3154896, sha256: '1e383df5b055583bc01cb5764ecdf74c540753f2cb3f8205e7105361da4bc989' },
  { code: 'mkd', name: 'Macedonian', file: 'mkd.traineddata', bytes: 1600188, sha256: '58622bf154830fa62103359938564aeb8112b929759e22a48224f3ecfaac34c6' },
  { code: 'msa', name: 'Malay', file: 'msa.traineddata', bytes: 1747801, sha256: 'e41a3e5febfec50c90371eb1cbb17a48b10cad387900e3420b1f134c1b766cba' },
  { code: 'nor', name: 'Norwegian', file: 'nor.traineddata', bytes: 3610079, sha256: '0451eb4f8049ae78196806bf878a389a2f40f1386fe038568cf4441226ba6ef2' },
  { code: 'fas', name: 'Persian', file: 'fas.traineddata', bytes: 431500, sha256: 'db1c0a91208aff00d3cf1ed2c1d23f76419afd5f024688b4f71adc3f2ce4a505' },
  { code: 'pol', name: 'Polish', file: 'pol.traineddata', bytes: 4765518, sha256: 'c4476cdbc0e33d898d32345122b7be1cbf85ace15f920f06c7714756e1ef79b2' },
  { code: 'por', name: 'Portuguese', file: 'por.traineddata', bytes: 1982756, sha256: 'c4932b937207a9514b7514d518b931a99938c02a28a5a5a553f8599ed58b7deb' },
  { code: 'ron', name: 'Romanian', file: 'ron.traineddata', bytes: 2376323, sha256: '9adfde6b51ba4b97efd10ea37c3070fd3fc2bad7815e81f5c3c198cd96216cc9' },
  { code: 'rus', name: 'Russian', file: 'rus.traineddata', bytes: 3861738, sha256: 'e16e5e036cce1d9ec2b00063cf8b54472625b9e14d893a169e2b0dedeb4df225' },
  { code: 'srp', name: 'Serbian (Cyrillic)', file: 'srp.traineddata', bytes: 2149931, sha256: 'aa41ae3d9cc705e60d398ab38a5c3cc8b772c0d420c7d4f0859beb13d0e321b6' },
  { code: 'srp_latn', name: 'Serbian (Latin)', file: 'srp_latn.traineddata', bytes: 3281787, sha256: '54b2e001bd8a336bdffc249c1487b8b7cb712f0a031f2551930ba050ebefa2a0' },
  { code: 'slk', name: 'Slovak', file: 'slk.traineddata', bytes: 4427661, sha256: 'fbcc400a9c74c6a13d922fcb1211b655d1b165387b675ed75cd2dbd756b974a5' },
  { code: 'slv', name: 'Slovenian', file: 'slv.traineddata', bytes: 3003829, sha256: 'b937632c17ce5fdf20535d25feec044da10a0c4c8234f4302d5606fd671cf60d' },
  { code: 'spa', name: 'Spanish', file: 'spa.traineddata', bytes: 2294433, sha256: '6f2e04d02774a18f01bed44b1111f2cd7f3ba7ac9dc4373cd3f898a40ea6b464' },
  { code: 'swe', name: 'Swedish', file: 'swe.traineddata', bytes: 4167034, sha256: 'f7304988d41f833efebcc2d529df54b1903ecebbc3da1faabd19a0fddd4fe586' },
  { code: 'tam', name: 'Tamil', file: 'tam.traineddata', bytes: 3237963, sha256: 'd02fbec24be4b07e32e80d0ccfc3b6b67a3c5d61c9d0a7c8532677990912c6ec' },
  { code: 'tha', name: 'Thai', file: 'tha.traineddata', bytes: 1072600, sha256: '294227cc2d1292b0acb28d61d4115c88252b96d466ca90b417cf4cf0c67bf07c' },
  { code: 'tur', name: 'Turkish', file: 'tur.traineddata', bytes: 4550554, sha256: '7393381111e1152420fc4092cb44eef4237580d21b92bf30d7d221aad192c6b7' },
  { code: 'ukr', name: 'Ukrainian', file: 'ukr.traineddata', bytes: 3825102, sha256: 'd59e53e2bded32f4445f124b4b00240fcac7e8044c003ab822ccb94f0b3db59b' },
  { code: 'urd', name: 'Urdu', file: 'urd.traineddata', bytes: 1398718, sha256: '62e8250ce2a994106e313a82e26a516a39e2cf159d0ce3c5b5008387fd0d555f' },
  { code: 'vie', name: 'Vietnamese', file: 'vie.traineddata', bytes: 531275, sha256: '79df64caf7bcfb2a27df5042ecb6121e196eada34da774956995747636d5bfa1' },
  { code: 'cym', name: 'Welsh', file: 'cym.traineddata', bytes: 2208919, sha256: '7f6ee3374749645a7c92dfe773f5c3d6492194d371712ecfd775edc53c363fb4' },
];
// </ocr-manifest>

const BY_CODE = new Map<string, OcrLanguageInfo>(OCR_LANGUAGES.map((l) => [l.code, l]));

/** The manifest entry for a tessdata code, or undefined when it is not installable. */
export function ocrLanguage(code: string | undefined | null): OcrLanguageInfo | undefined {
  return typeof code === 'string' ? BY_CODE.get(code) : undefined;
}

export function isOcrLanguageCode(code: unknown): code is string {
  return typeof code === 'string' && BY_CODE.has(code);
}

/** Download URL of a manifest language. */
export function ocrLanguageUrl(lang: OcrLanguageInfo): string {
  return TESSDATA_BASE + lang.file;
}

/**
 * Track language tag → tessdata code, for tags that are not already a tessdata code: ISO 639-1 (2 letters),
 * ISO 639-2/B where it differs from /T, and a few common variants. ISO 639-2/T codes are mostly tessdata codes
 * themselves and are matched directly.
 */
const TAG_TO_TESSDATA: Record<string, string> = {
  // ISO 639-2/B → tessdata (= 639-2/T)
  fre: 'fra', ger: 'deu', dut: 'nld', cze: 'ces', gre: 'ell', rum: 'ron', slo: 'slk', per: 'fas', ice: 'isl',
  mac: 'mkd', may: 'msa', alb: 'sqi', arm: 'hye', baq: 'eus', geo: 'kat', wel: 'cym', bur: 'mya', tib: 'bod',
  chi: 'chi_sim', zho: 'chi_sim', scc: 'srp', scr: 'hrv',
  // other 639-2 / 639-3 variants
  nob: 'nor', nno: 'nor', tgl: 'fil', zsm: 'msa', cmn: 'chi_sim', yue: 'chi_tra', pes: 'fas', prs: 'fas',
  arb: 'ara', ekk: 'est', lvs: 'lav', hbs: 'srp_latn', sh: 'srp_latn',
  // ISO 639-1
  en: 'eng', fr: 'fra', de: 'deu', es: 'spa', it: 'ita', pt: 'por', nl: 'nld', sv: 'swe', no: 'nor', nb: 'nor', nn: 'nor',
  da: 'dan', fi: 'fin', pl: 'pol', cs: 'ces', sk: 'slk', hu: 'hun', ro: 'ron', el: 'ell', ru: 'rus', uk: 'ukr',
  bg: 'bul', sr: 'srp', hr: 'hrv', sl: 'slv', bs: 'bos', mk: 'mkd', sq: 'sqi', tr: 'tur', ar: 'ara', he: 'heb',
  iw: 'heb', fa: 'fas', hi: 'hin', bn: 'ben', ta: 'tam', te: 'tel', ur: 'urd', th: 'tha', vi: 'vie', id: 'ind',
  in: 'ind', ms: 'msa', ja: 'jpn', ko: 'kor', zh: 'chi_sim', is: 'isl', et: 'est', lv: 'lav', lt: 'lit', ca: 'cat',
  gl: 'glg', eu: 'eus', cy: 'cym', ga: 'gle', hy: 'hye', ka: 'kat', be: 'bel', tl: 'fil', af: 'afr', sw: 'swa',
  ml: 'mal', kn: 'kan', mr: 'mar', gu: 'guj', pa: 'pan', ne: 'nep', si: 'sin', km: 'khm', lo: 'lao', my: 'mya',
  kk: 'kaz', az: 'aze', uz: 'uzb', mn: 'mon', la: 'lat', eo: 'epo', lb: 'ltz', mt: 'mlt',
};

/** Region / script subtags that pick traditional Chinese. */
const CHI_TRA_HINTS = new Set(['hant', 'tw', 'hk', 'mo']);

/**
 * Best tessdata code for a track language tag (`fre`, `fr`, `fr-CA`, `zh-Hant`, `chi`, ...), or null when the
 * tag is missing, undetermined (`und`, `unknown`, `mis`, `mul`, `zxx`) or names a language not in OCR_LANGUAGES.
 */
export function guessOcrLanguage(tag?: string | null): string | null {
  if (typeof tag !== 'string') return null;
  const parts = tag.trim().toLowerCase().split(/[-_]/).filter(Boolean);
  if (parts.length === 0) return null;
  const [primary, ...rest] = parts;
  // A full tessdata code with an underscore (chi_sim, srp_latn) given as-is.
  const whole = parts.join('_');
  if (BY_CODE.has(whole)) return whole;
  let code = BY_CODE.has(primary) ? primary : TAG_TO_TESSDATA[primary];
  if (!code) return null;
  if (code === 'chi_sim' && rest.some((p) => CHI_TRA_HINTS.has(p))) code = 'chi_tra';
  if (code === 'srp' && rest.includes('latn')) code = 'srp_latn';
  return BY_CODE.has(code) ? code : null;
}

/** tessdata codes whose ISO 639-2/B tag differs from the code (or which have no 3-letter code of their own). */
const TESSDATA_TO_ISO6392B: Record<string, string> = {
  fra: 'fre', deu: 'ger', nld: 'dut', ces: 'cze', ell: 'gre', ron: 'rum', slk: 'slo', fas: 'per', isl: 'ice',
  mkd: 'mac', msa: 'may', sqi: 'alb', hye: 'arm', eus: 'baq', kat: 'geo', cym: 'wel', mya: 'bur', bod: 'tib',
  chi_sim: 'chi', chi_tra: 'chi', srp_latn: 'srp',
};

/**
 * ISO 639-2/B language tag for a track read with tessdata `code` (what Matroska and ffprobe use): `fra` → `fre`,
 * `chi_sim` → `chi`; codes that are already 639-2 come back unchanged.
 */
export function iso6392ForOcr(code: string): string {
  return TESSDATA_TO_ISO6392B[code] ?? code.split('_')[0];
}

/** Start OCR of one bitmap subtitle stream (runs as a job of kind 'ocr'). */
export interface OcrRequest {
  mediaId: ID;
  /** Source media file. */
  path: string;
  /** Absolute ffprobe stream index of the bitmap subtitle stream. */
  streamIndex: number;
  /** tessdata code from OCR_LANGUAGES; must be installed. */
  language: string;
  /** The stream's codec as probed (informational; the job probes it again). */
  codec?: string;
}

/** `JobInfo.result` of a finished 'ocr' job. */
export interface OcrResult {
  mediaId: ID;
  streamIndex: number;
  language: string;
  codec: string;
  /** Recognized cues, source seconds. */
  cues: SubtitleCue[];
  /** Number of subtitle events (images) read from the stream. */
  events: number;
  /** True when the result came from the OCR cache instead of a new run. */
  cached: boolean;
}

/** One row of `ocrLanguages()`: a manifest language and whether it is installed. */
export interface OcrLanguageState {
  code: string;
  name: string;
  bytes: number;
  /** The file is in the OCR data folder with the manifest size. */
  installed: boolean;
  /** Id of the running or queued 'download' job installing it, if any. */
  jobId?: string;
}
